trigger:
  branches:
    include:
      - main
 
pool:
  name: 'vm-npr-job-app-dev-10'  # Specify the specific VM pool
 
stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        timeoutInMinutes: 1400  # Set the timeout to 24 hours
        displayName: Build Job
        pool:
          name: 'vm-npr-job-app-dev-10'  # Ensure the job runs on the specified VM
        steps:
          - script: |
             echo "Updating npm to the latest version..."
             npm install -g npm@latest
             npm -v
            displayName: 'Update npm to the latest version'
          # Checkout the repository and specific branch
          - checkout: self  # Use self for the default repository
            persistCredentials: true
            clean: true
            fetchDepth: 0
            submodules: true
          # Install npm dependencies and playwright dependencies
          - task: Bash@3
            displayName: Install npm dependencies
            inputs:
              targetType: inline
              script: |
                npm install 
                npm i
                npx playwright install-deps
                npx playwright install
                npm install winston moment-timezone
                npm install @types/winston @types/moment-timezone
          # Run the tests using xvfb-run and npm run test
          - task: CmdLine@2
            inputs:
             script: |
              xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' npm run test
            displayName: Running test

          # Step to publish reports as artifacts
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/test-result/report' 
              ArtifactName: 'TestReports'
              publishLocation: 'Container'  
